# Generated by Django 6.0.4 on 2026-04-30 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requests_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('file_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_type_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.FileField(upload_to='media_files/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='media.filetype')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='requests_app.request')),
            ],
        ),
    ]
