# Generated by Django 6.0.4 on 2026-05-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('request_submitted', 'Request Submitted'), ('request_approved', 'Request Approved'), ('request_rejected', 'Request Rejected'), ('request_updated', 'Request Updated'), ('general', 'General')], default='general', max_length=50),
        ),
    ]
