# Generated by Django 6.0.4 on 2026-04-30 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('platform_id', models.AutoField(primary_key=True, serialize=False)),
                ('platform_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('social_media', 'Request for Social Media Announcements, Social Media Cards, Write Ups, and Communications'), ('image_editing', 'Request for Image Layout or Editing'), ('printed_media', 'Request for Printed Media (Image, Invitations, Certificate, ID Cards, Tarpaulin)'), ('photo_coverage', 'Request Photo Coverage for Documentation (Soft Copy)'), ('video_coverage', 'Request Video Coverage for Documentation (Soft Copy)'), ('video_editing', 'Request Video Editing'), ('radio_program', 'Request Radio Program Announcement and Guesting/Interviews'), ('live_streaming', 'Request for Live Video Streaming (Zoom, Youtube Live, Facebook Live)'), ('it_repair', 'Request for IT Equipment Repair/Maintenance'), ('leave_absence', 'Application for Leave of Absence')], default='social_media', max_length=50)),
                ('details', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Requester',
            fields=[
                ('requester_id', models.AutoField(primary_key=True, serialize=False)),
                ('agency_name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=150)),
                ('contact_number', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('publication_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_link', models.URLField(blank=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('platform', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='requests_app.platform')),
                ('published_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='requests_app.request')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessingLog',
            fields=[
                ('process_id', models.AutoField(primary_key=True, serialize=False)),
                ('action_taken', models.TextField()),
                ('process_step', models.CharField(max_length=100)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_logs', to='requests_app.request')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('attachment_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.FileField(upload_to='attachments/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='requests_app.request')),
            ],
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('approval_id', models.AutoField(primary_key=True, serialize=False)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='requests_app.request')),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='requests_app.requester'),
        ),
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='requests_app.status'),
        ),
    ]
