# Generated by Django 6.0.4 on 2026-05-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requester',
            name='barangay',
            field=models.CharField(blank=True, choices=[('adia_bitaog', 'Adia Bitaog'), ('anonangin', 'Anonangin'), ('bagong_buhay', 'Bagong Buhay (Poblacion)'), ('bamban', 'Bamban'), ('bantad', 'Bantad'), ('batong_dalig', 'Batong Dalig'), ('biga', 'Biga'), ('binambang', 'Binambang'), ('buensuceso', 'Buensuceso'), ('bungahan', 'Bungahan'), ('butaguin', 'Butaguin'), ('calumangin', 'Calumangin'), ('camohaguin', 'Camohaguin'), ('casasahan_ibaba', 'Casasahan Ibaba'), ('casasahan_ilaya', 'Casasahan Ilaya'), ('cawayan', 'Cawayan'), ('gayagayaan', 'Gayagayaan'), ('gitnang_barrio', 'Gitnang Barrio'), ('hagakhakin', 'Hagakhakin'), ('hardinan', 'Hardinan'), ('inaclagan', 'Inaclagan'), ('inagbuhan_ilaya', 'Inagbuhan Ilaya'), ('labnig', 'Labnig'), ('laguna', 'Laguna'), ('lagyo', 'Lagyo'), ('mabini', 'Mabini (Poblacion)'), ('mabunga', 'Mabunga'), ('malabtog', 'Malabtog'), ('manlayaan', 'Manlayaan'), ('marcelo_h_del_pilar', 'Marcelo H. del Pilar'), ('mataas_na_bundok', 'Mataas na Bundok'), ('maunlad', 'Maunlad (Poblacion)'), ('pagsabangan', 'Pagsabangan'), ('panikihan', 'Panikihan'), ('penafrancia', 'Peñafrancia (Poblacion)'), ('pipisik', 'Pipisik (Poblacion)'), ('progreso', 'Progreso'), ('rizal', 'Rizal (Poblacion)'), ('rosario', 'Rosario'), ('san_agustin', 'San Agustin'), ('san_diego_bukid', 'San Diego (Bukid)'), ('san_diego_poblacion', 'San Diego (Poblacion)'), ('san_isidro_kanluran', 'San Isidro Kanluran'), ('san_isidro_silangan', 'San Isidro Silangan'), ('san_juan_de_jesus', 'San Juan de Jesus'), ('san_vicente', 'San Vicente'), ('sastre', 'Sastre'), ('tabing_dagat', 'Tabing Dagat (Poblacion)'), ('tumayan', 'Tumayan'), ('villa_arcaya', 'Villa Arcaya'), ('villa_bota', 'Villa Bota'), ('villa_fuerte', 'Villa Fuerte'), ('villa_mendoza', 'Villa Mendoza'), ('villa_nava', 'Villa Nava'), ('villa_padua', 'Villa Padua'), ('villa_perez', 'Villa Perez'), ('villa_principe', 'Villa Principe'), ('villa_tanada', 'Villa Tañada'), ('villa_victoria', 'Villa Victoria')], max_length=100, null=True),
        ),
    ]
