# Generated by Django 6.0.4 on 2026-05-04 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0003_request_result_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='published_by',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='request',
        ),
        migrations.DeleteModel(
            name='Platform',
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
    ]
